### ISSUE TITLE
Error "Unsupported major.minor version 51.0" with Play 2.2.1 / sbt 0.13.0

### ISSUE THREAD

**Issue by dyross** [laughedelic/literator#13]
I get this error when I run `sbt` in the root dir:

    [error] java.lang.UnsupportedClassVersionError: laughedelic/literator/plugin/LiteratorPlugin$Literator$ : Unsupported major.minor version 51.0
    [error] Use 'last' for the full log.

Trivial example:

https://github.com/dyross/test-literator-play

**Comment by laughedelic** [comment]
Closing this. Hopefully, everybody's using java-7 already.. :smile:
